### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by masx200** [egregors/TreeNode#2]
```
 go run main.go
[1,2,3,4,5,6,7,8,9,10,11,12,13,null,null,15]
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/egregors/TreeNode.bfsBuild(0xc000079ce0, {0xc0001000f0?, 0x13ac59d0108?, 0xc000079cd0?})
        C:/Users/Administrator/go/pkg/mod/github.com/egregors/!tree!node@v1.0.3/tree.go:100 +0x3c5
github.com/egregors/TreeNode.bfsBuild(0xc000079d98, {0xc000100070?, 0x13ac59d0108?, 0xc000079d88?})
        C:/Users/Administrator/go/pkg/mod/github.com/egregors/!tree!node@v1.0.3/tree.go:123 +0x39b
github.com/egregors/TreeNode.bfsBuild(0xc000079e50, {0xc000100030?, 0xaecb3f?, 0xc000079e40?})
        C:/Users/Administrator/go/pkg/mod/github.com/egregors/!tree!node@v1.0.3/tree.go:123 +0x39b
github.com/egregors/TreeNode.bfsBuild(0xc000079ee8, {0xc000100010?, 0xb956dd?, 0x1?})
        C:/Users/Administrator/go/pkg/mod/github.com/egregors/!tree!node@v1.0.3/tree.go:123 +0x39b
github.com/egregors/TreeNode.NewTreeNode({0xb9dbf4?, 0xc00000a018?})
        C:/Users/Administrator/go/pkg/mod/github.com/egregors/!tree!node@v1.0.3/tree.go:32 +0x179
main.main()
        C:/Users/Administrator/go/temp/main.go:14 +0x76
exit status 2
```
go.mod
```
module temp

go 1.19

require github.com/egregors/TreeNode v1.0.3

```
main.go
```go
package main

import (
	"fmt"
	"log"

	tn "github.com/egregors/TreeNode"
)

func main() {
	data := "[1,2,3,4,5,6,7,8,9,10,11,12,13,null,null,15]"
	fmt.Println(data)

	root, err := tn.NewTreeNode(data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(root)
}
```
go version go1.19 windows/amd64

**Comment by masx200** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/34191203/185751914-3d7282dd-74b6-4fbb-a53b-e00cfea259d5.png">

**Comment by masx200** [comment]
https://leetcode-cn.com/problems/serialize-and-deserialize-binary-tree/

**Comment by egregors** [comment]
@masx200 well done! 👍 👍 👍 Thanks for your contributing. All your PR's merged. Check v.1.0.3 version.
